# Generated by Django 4.2.23 on 2025-07-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoleManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_role', 'Can view roles'), ('add_role', 'Can add roles'), ('change_role', 'Can change roles'), ('delete_role', 'Can delete roles')],
                'managed': False,
            },
        ),
    ]
