# Generated by Django 4.2.23 on 2025-07-28 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoleManagement',
        ),
    ]
